version: "3"
services:

  website-php7:
    build:
      context: .
      dockerfile: Dockerfile
    image: ztj1993/website-php7:latest
    hostname: website-php7
    container_name: website-php7
    network_mode: custom
    volumes:
      - /etc/localtime:/etc/localtime:ro
    expose:
      - 80/tcp
      - 443/tcp
    ports:
      - 80/tcp
